---
title: "More information"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---

<!--
Comments in HTML are like this! 
-->

# Source

Our data was sourced from Yamaç Eren Ay's  [post](https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks) on kaggle which was in turn obtained from [Spotify](https://developer.spotify.com/documentation/web-api/reference/tracks/get-track/).

# Parameters

The following is the description about the individual parameters given by Spotify

## Energy

Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy. It can be found [here](https://developer.spotify.com/documentation/web-api/reference/tracks/get-track/) 

## Popularity

The popularity of the track. The value will be between 0 and 100, with 100 being the most popular.
The popularity of a track is a value between 0 and 100, with 100 being the most popular. The popularity is calculated by algorithm and is based, in the most part, on the total number of plays the track has had and how recent those plays are.
Generally speaking, songs that are being played a lot now will have a higher popularity than songs that were played a lot in the past. Duplicate tracks (e.g. the same track from a single and an album) are rated independently. Artist and album popularity is derived mathematically from track popularity. Note that the popularity value may lag actual popularity by a few days: the value is not updated in real time.

## Acousticness

A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic. 


## Explicit

Whether or not the track has explicit lyrics ( true = yes it does; false = no it does not OR unknown).
